---
title: Monty Hall problem
author: Guo Te
date: '2022-07-20'
slug: monty-hall-problem
categories:
  - R
tags:
  - R Markdown
editor_options: 
  chunk_output_type: console
---


### 三门问题路径分析

三门问题（Monty Hall problem）亦称为蒙提霍尔问题、蒙特霍问题或蒙提霍尔悖论，大致出自美国的电视游戏节目Let's Make a Deal。问题名字来自该节目的主持人蒙提·霍尔（Monty Hall）。参赛者会看见三扇关闭了的门，其中一扇的后面有一辆汽车，选中后面有车的那扇门可赢得该汽车，另外两扇门后面则各藏有一只山羊。



三门背后对应内容：1个Car, 2只羊（Goat1 , Goat2）

三门问题一直以来困扰很多人，我们先看下面的路线图

```{r echo=FALSE}
library(DiagrammeR)
grViz("
digraph flowchart{
rankdir=LR; 

node[fontname='Arial Black', fillcolor='#9DD6DF', color='#FF0063', style=filled, shape=oval]
participant;car_door;goat_door; goat;

node[fontname='Arial Black', fillcolor='white', color='#EB1D36', style=filled, shape=oval]
car;

edge[fontname=arial, color=blue, style=filled, arrowhead=vee]

participant -> car_door [label='1/3', fontsize=10]
car_door -> goat [label='switch', fontsize=10, color='red']
car_door -> car  [label='keep', fontsize=10, color='green']
participant -> goat_door [label='2/3', fontsize=10]
goat_door -> car [label='switch', fontsize=10, color='red']
goat_door -> goat  [label='keep', fontsize=10,color='green']


#subgraph{rank=same; D;B}
#subgraph{rank=same; C}

}",
height = 400)
```

### 如果我们只关心能不能得到汽车。

1. 从car 节点上看，keep策略1/3 * 1， switch策略2/3 * 1 . 
```{r echo=FALSE}
library(DiagrammeR)
grViz("
digraph flowchart{
rankdir=LR; 

node[fontname='Arial Black', fillcolor='#9DD6DF', color='#FF0063', style=filled, shape=oval]
participant;car_door;goat_door; goat;

node[fontname='Arial Black', fillcolor='white', color='#EB1D36', style=filled, shape=oval]
car;

edge[fontname=arial, color=blue, style=filled, arrowhead=vee]

participant -> car_door [label='1/3', fontsize=10]

car_door -> car  [label='keep', fontsize=10, color='green']
participant -> goat_door [label='2/3', fontsize=10]
goat_door -> car [label='switch', fontsize=10, color='red']



#subgraph{rank=same; D;B}
#subgraph{rank=same; C}

}",
height = 400)
```
2. 从goat节点上看，keep策略2/3 * 1， switch策略1/3 * 1 .

```{r echo=FALSE}
library(DiagrammeR)
grViz("
digraph flowchart{
rankdir=LR; 

node[fontname='Arial Black', fillcolor='#9DD6DF', color='#FF0063', style=filled, shape=oval]
participant;car_door;goat_door; goat;

node[fontname='Arial Black', fillcolor='white', color='#EB1D36', style=filled, shape=oval]
car;

edge[fontname=arial, color=blue, style=filled, arrowhead=vee]

participant -> car_door [label='1/3', fontsize=10]
car_door -> goat [label='switch', fontsize=10, color='red']
 
participant -> goat_door [label='2/3', fontsize=10]

goat_door -> goat  [label='keep', fontsize=10,color='green']


#subgraph{rank=same; D;B}
#subgraph{rank=same; C}

}",
height = 400)
```
